### PR TITLE
Exact interactions

### PR DESCRIPTION
**Pull request by mwojcikowski**
An option to include exact representation of a structure instead of implying tautomers, ionizations etc.

### CODE REVIEW

**Comment by tdudgeon** [comment]
The exact mode is not working for me. I'm using RDKit as toolkit.
When I specify:

    protein_atoms, ligand_atoms, strict = oddt.interactions.hbonds(protein, mol, mol2_exact=True)

this happens:
```
Traceback (most recent call last):
  File "/home/timbo/github/im/pipelines/src/python/pipelines/xchem/calc_interactions.py", line 222, in process
    inter_data = process_mol(protein, ligand, key_inters, total, filter_strict=filter_strict, compare_data=compare_data)
  File "/home/timbo/github/im/pipelines/src/python/pipelines/xchem/calc_interactions.py", line 259, in process_mol
    inters = calc_hydrogen_bond_interactions(protein, mol, key_inters.get(interactions.I_TYPE_HBOND, None), mol_key_inters, filter_strict=filter_strict)
  File "/home/timbo/github/im/pipelines/src/python/pipelines/xchem/calc_interactions.py", line 380, in calc_hydrogen_bond_interactions
    protein_atoms, ligand_atoms, strict = oddt.interactions.hbonds(protein, mol, mol2_exact=True)
  File "/home/timbo/miniconda3/envs/pipelines-utils-oddt-exact-interactions/lib/python3.7/site-packages/oddt/interactions.py", line 157, in hbonds
    a1, d1, s1 = hbond_acceptor_donor(mol1, mol2, cutoff=cutoff, tolerance=tolerance, donor_exact=mol2_exact)
  File "/home/timbo/miniconda3/envs/pipelines-utils-oddt-exact-interactions/lib/python3.7/site-packages/oddt/interactions.py", line 108, in hbond_acceptor_donor
    donor_mask &= mol2.atom_dict['numhs'] > 0
ValueError: output array is read-only
```

Specifying False works OK.

**Comment by tdudgeon** [comment]
@mwojcikowski I tested this out and I think it's working as expected. That's both for h-bonds and salt bridges.
So I hope this is good to merge now.

**Comment by tdudgeon** [comment]
@mwojcikowski A related question on the presence of hydrogens.
If the protein and/or the ligand have all hydrogens present will this impact the predicted interactions.
I ask because I've had a request from a comp chemist that hydrogens on the ligand should not be removed when writing the results. I write the interaction data to a SDF as properties that are added to the molecules and as Hs are removed when reading the molecules from the input SDF they are missing from the results.
I think there are 2 parts to this:
1. can the Hs be retained on reading the SDF
2. If Hs are present will it impact the interactions

**Comment by mwojcikowski** [comment]
Having Hs explicitly in molecular graph should not affect the interaction analysis. In the same way as `[NH]` pattern will match to both `[NH]` smiles and to `[N][H]` smiles (contrary to `[N][#1]` which only matches the latter).

Regarding saving to SDF I see no arguments in RDKit to remove Hs during write, so they are probably removed during reading. I  don't see a way of passing an argument to SDF reader, but that is an oversight an I will try to address it in a separate PR.

**Pull request merged**
