### PR TITLE
Add option to generate bits info for PLEC fingerprints

### PR DESCRIPTION
**Pull request by mwojcikowski**
Addresses #118 

@luponzo86 Could you check if this branch works for you? The return API has not changed the `bits_info` dictionary is modified in-place, so you need to feed an instance to PLEC fp.

```python
bits_info = {}
PLEC(ligand, protein, bits_info=bits_info)
print(bits_info)
```

The dictionary contains mapping between bits and ligand/protein root atom IDXs plus the depths. Let me know what you think about this capability.

### CODE REVIEW

**Comment by luponzo86** [comment]
Hi @mwojcikowski 
that's great, thank you so much!
I tried it out and it works perfectly :) 

Just a quick follow-up question: 
Now that I have the root atoms for each bit, e.g.:
```
{'ligand_root_atom_idx': 4,
 'ligand_depth': 2,
 'protein_root_atom_idx': 9,
 'protein_depth': 2}
```
if I want to find all atoms involved in this "substructure" (both in the protein and in the ligand), I was thinking of writing something similar to this function:
https://github.com/oddt/oddt/blob/c57a9ccee0395fb7fa7e5dd75bd2ef4cfc5ee3ab/oddt/fingerprints.py#L429
to recover the `atom[env]` list: https://github.com/oddt/oddt/blob/c57a9ccee0395fb7fa7e5dd75bd2ef4cfc5ee3ab/oddt/fingerprints.py#L489
 
Is that correct? At the end, I'd like to use that atom selection to visualize the interacting atoms in a PyMol session.

Thanks again!
Luca

**Comment by mwojcikowski** [comment]
Yes, this seem correct. 

To make your life easier I have extracted a function called `get_atom_environments` that will extract the indices you want. If you use RDKit use `Chem.MolFragmentToSmiles` to easily get the SMILES of interacting fragments.

I will think of a universal way of visualising the fragments. Any suggestions?
Going to Pymol with the visualization sounds **really** cool, although it's probably out of scope for ODDT, but generating SMILES is probably fine too.

**Comment by luponzo86** [comment]
That is cool and very helpful, thanks!

I think having all this information printed out for each bit is already a very flexible way to interface with any library, including for visualization

Thank you so much!

Luca

**Comment by luponzo86** [comment]
Hi @mwojcikowski ,

sorry to bother you again.
I was playing around with your implementation of `bits_info` today and I may have found a couple of  issues.

1. Backstory: I wanted to use `bits_info` to understand why two PLEC fingerprints for the same molecule, imported by OpenBabel with and without hydrogens explicitly removed (`mol.removeh()`), were different. It turns out that if you try to remove Hs on a molecule where PLEC was already computed, you'll encounter some inconsistencies. Maybe this code snippet will make it clear:

```
# random filenames (I cannot share the PDBs I am using)
p = 'protein.pdbqt'
l = 'ligand.pdbqt'

# import molecules with OpenBabel
rec = next(pybel.readfile('pdbqt', p))
lig = next(pybel.readfile('pdbqt', l))

# compute PLEC
bi = {}
plec = PLEC(
    lig, protein=rec, size=1024, bits_info=bi)

#################################
# Now let's remove Hs from the *same* molecules
# (enviroments are precomputed and won't change?)
rec.removeh()
lig.removeh()

# compute PLEC
bi_rh = {}
plec_rh = PLEC(
    lig, protein=rec, size=1024, bits_info=bi_rh)

#################################
# Now, let's create *new* molecules and remove Hs
rec = next(pybel.readfile('pdbqt', p))
lig = next(pybel.readfile('pdbqt', l))
rec.removeh()
lig.removeh()

# ...and compute PLEC
bi_rh2 = {}
plec_rh2 = PLEC(
    lig, protein=rec, size=1024, bits_info=bi_rh2)

###############################
# COMPARISON
assert( np.allclose(plec, plec_rh) )  # <-- they are the same
assert( np.allclose(plec, plec_rh2) )  # <-- they are different
```
Moreover, `bi`, `bi_rh` and `bi_rh2` will all be different from each other.

2. I realized now that in most cases there will be bit collision in FPs, so in that case a bit in `bits_info` should map to multiple environments?

Thank you so much for doing this, I hope my feedback will be useful!

Luca

**Comment by mwojcikowski** [comment]
Oh, that was quite big oversight on my side. Multiple root atoms may lead to the same bits, which was lost by previous commit. Now I improved it, and the bit info entries are `namedtuple` now and stored in a set. Plus we have collisions, and they will be handled too.

Regarding the error you observe. The problem is with the loading of molecules. Please use `oddt.toolkit.readfile` instead of `pybel.readfile`, that should fix the issue. ODDT molecules use `Molecule.atom_dict` numpy array to store heavily used data, like atom coords, idxs and many more. Obviously after adding removing Hs this info is not accurate, and ODDT `Molecule` object override `addh` and `removeh` methods to clear that cache.

https://github.com/oddt/oddt/blob/da6064886c15b53ec205b17f4d22252376e8e6c5/oddt/toolkits/ob.py#L249-L260

Using `oddt.toolkit.Molecule` instances from the start should be free of observed issue.

**Comment by luponzo86** [comment]
That's great!
Thank you so much!

**Comment by luponzo86** [comment]
Hi @mwojcikowski ,
I think I may have found a bug in the implementation of `bit_info`.
When inspecting the results on a few examples, I noticed that ECFP environments from the same protein/ligand root atoms, but with different depths, often ended up mapped to the same bit. For instance (I won't attach the code, just a printed log):
```
>>> Bit 6 has count 2 >>>>>>>>>>>>>>>>>>>>>>>

PLEC_bit_info_record(ligand_root_atom_idx=10, ligand_depth=1, protein_root_atom_idx=8, protein_depth=1)
prot. env.: [[8], [12, 9, 6]]
lig. env.: [[10], [9]]

PLEC_bit_info_record(ligand_root_atom_idx=10, ligand_depth=0, protein_root_atom_idx=8, protein_depth=0)
prot. env.: [[8]]
lig. env.: [[10]]

>>> Bit 9 has count 4 >>>>>>>>>>>>>>>>>>>>>>>

PLEC_bit_info_record(ligand_root_atom_idx=10, ligand_depth=2, protein_root_atom_idx=8, protein_depth=4)
prot. env.: [[8], [12, 9, 6], [5], [4], [3]]
lig. env.: [[10], [9], [7, 11]]

PLEC_bit_info_record(ligand_root_atom_idx=10, ligand_depth=2, protein_root_atom_idx=8, protein_depth=3)
prot. env.: [[8], [12, 9, 6], [5], [4]]
lig. env.: [[10], [9], [7, 11]]

PLEC_bit_info_record(ligand_root_atom_idx=10, ligand_depth=2, protein_root_atom_idx=8, protein_depth=2)
prot. env.: [[8], [12, 9, 6], [5]]
lig. env.: [[10], [9], [7, 11]]

PLEC_bit_info_record(ligand_root_atom_idx=11, ligand_depth=0, protein_root_atom_idx=8, protein_depth=0)
prot. env.: [[8]]
lig. env.: [[11]]
```

I think there is an error at this [line](https://github.com/oddt/oddt/blob/f56e142c62b9ea66daebbde1199dccf7adfe1378/oddt/fingerprints.py#L834)

After folding, the bits are sorted, but the list `bit_info_content` is not. Therefore, the `zip()` command at this [line](https://github.com/oddt/oddt/blob/f56e142c62b9ea66daebbde1199dccf7adfe1378/oddt/fingerprints.py#L838) assigns the wrong (unsorted) `atom_info`'s to each bit.

I guess a simple fix would be to sort `bit_info_content` together with `plec`, by storing the sorting indexes from `np.argsort()`

Hope this helps!

Luca

**Comment by mwojcikowski** [comment]
@luponzo86 I modified the code a bit to avoid additional loop over all bits . Also without mapping bits performance should be the same as before the changes.

**Pull request merged**
